name: Generate Terraform Documentation
on: [push, pull_request]

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Generate documentation for main module
        run: |
          docker run --rm -v $(pwd):/workspace quay.io/terraform-docs/terraform-docs:latest markdown table --output-file README.md --output-mode inject /workspace

      - name: Generate documentation for subnet submodule
        run: |
          docker run --rm -v $(pwd)/subnet:/workspace quay.io/terraform-docs/terraform-docs:latest markdown table --output-file README.md --output-mode inject /workspace
