name: Generate Terraform Documentation
on: [push, pull_request]

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Generate documentation for main module
        uses: terraform-docs/gh-actions@v0.10.1
        with:
          working-dir: .
          output-file: README.md
          output-method: inject

      - name: Generate documentation for subnet submodule
        uses: terraform-docs/gh-actions@v0.10.1
        with:
          working-dir: ./subnet/
          output-file: README.md
          output-method: inject
